import { Roboto } from "next/font/google";
import type { Metadata } from "next";

import "./styles/globals.css";
import { Toaster } from "@/components/ui/toaster";

const font = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "BalanceWise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
